version: '3.8'
name: vscode-container
services:
  vscode-server:
    build: .
    ports:
      - "6321:3000"
    container_name: vscode-container
    image: "vscode-server"
    volumes:
      - '../certbot/nhvu95.com:/etc/nginx/cert'
    restart: unless-stopped
networks:
    default:
      name: tunnel
      external: true